name = "laslogtmx-web"
compatibility_date = "2026-06-21"
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "laslogtmx-web"
routes = [
  { pattern = "laslogtmx.com", custom_domain = true },
  { pattern = "app.laslogtmx.com", custom_domain = true },
]

[env.staging]
name = "laslogtmx-web-staging"
routes = [
  { pattern = "dev.laslogtmx.com", custom_domain = true },
]