name = "laslogtmx-marketing"
compatibility_date = "2026-06-21"
pages_build_output_dir = "out"

[env.production]
name = "laslogtmx-marketing"
routes = [
  { pattern = "laslogtmx.com", custom_domain = true },
]

[env.staging]
name = "laslogtmx-marketing-staging"
routes = [
  { pattern = "dev.laslogtmx.com", custom_domain = true },
]
